### PR TITLE
Don't remove just some jobs from inside the transaction; just enqueue them

### PR DESCRIPTION
**Pull request by ukd1**
This is related to #6, and might make things a little more fair if one of theories is correct.

### CODE REVIEW

**Comment by ukd1** [comment]
FYI @bensheldon I'm not sure where the delete / destroy behavior is in the ``good_job`` code; It didn't seem to be obviously deleting it after each job, but I might have missed it.

**Comment by bensheldon** [comment]
@ukd1 `good_job` deletes the job inside of `GoodJob::Job.perform_with_advisory_lock`, which calls `GoodJob::Job#perform` which calls destroy: https://github.com/bensheldon/good_job/blob/fe3eb50c1c9ae94283b0aa5960fa135ad32dea6f/lib/good_job/job.rb#L218-L225

I think it could be clearer by explicitly setting `GoodJob.preserve_job_records = false` in the setup code here.

That all being said, I don't have a clue why `good_job` has such huge standard deviation; my hypothesis is that the advisory lock query (which relies on a materialized CTE) is thrashy, but I am not a Postgres DBA :-(

**Comment by ukd1** [comment]
@bensheldon ya, likely some of them perform so well as everything is done, and undone in the transaction? I might be wrong though. IMHO, deleting the enqueued item isn't a realistic benchmark, doubly so when not every queue is doing it.

Re advisory locks, depends which type you're using - one is session based (i.e. until you disconnect, outside of transactions e.g. ``pg_advisory_lock``), the other transaction based (e.g. ``pg_advisory_xact_lock``).

**Comment by bensheldon** [comment]
@ukd1 sorry it took me a minute to merge 😓 Thank you so much! 🙏🏻

**Comment by ukd1** [comment]
> @ukd1 sorry it took me a minute to merge 😓 Thank you so much! 🙏🏻

No worries, thanks for merging!

**Pull request merged**
